apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-08-06 
  janus-idp.io/tekton: test-08-06
  backstage.io/kubernetes-id: test-08-06
  backstage.io/kubernetes-namespace: rhdh 
  app.kubernetes.io/part-of: test-08-06
resources: 
- application-dev.yaml